{{- if .Values.externalSecret.enabled }}
{{- if not .Values.externalSecret.useExternalSecretOperator }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "service.externalSecretName" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  backendType: {{ .Values.externalSecret.backendType }}
{{- if eq .Values.externalSecret.backendType "vault" }}
  vaultMountPoint: {{ .Values.externalSecret.vaultMountPoint }}
  vaultRole: {{ .Values.externalSecret.vaultRole }}
{{- end }}
{{- if .Values.externalSecret.dataVars }}
  data:
    {{- range $key, $value :=  .Values.externalSecret.dataVars }}
    - name: {{ $key }}
      {{- $value | toYaml | nindent 6 }}
    {{- end }}
{{- else if .Values.externalSecret.data }}
  data:
  {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
{{- if .Values.externalSecret.dataFrom }}
  dataFrom:
  {{- range .Values.externalSecret.dataFrom }}
    - {{ . }}
  {{- end }}
{{- end }}
---
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "service.externalSecretName" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ default "vault-dhhmena" .Values.externalSecret.secretStore }}
    kind: ClusterSecretStore

{{- if .Values.externalSecret.dataFrom }}
  dataFrom:
  {{- range .Values.externalSecret.dataFrom }}
  {{- if kindIs "string" . }}
    - extract:
        key: {{ tpl . $ }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  {{- else }}
    - extract:
        key: {{ tpl .key $ }}
        version: {{ .version | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  {{- end }}
  {{- end }}
{{- end }}

{{- if or .Values.externalSecret.dataVars .Values.externalSecret.data }}
  data:
  {{- if .Values.externalSecret.dataVars }}
    {{- range $key, $value := .Values.externalSecret.dataVars }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ tpl $value.key $ }}
        property: {{ tpl ($value.property | default "") $ }}
        version: {{ $value.version | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
  {{- end }}
  {{- if .Values.externalSecret.data }}
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ tpl .key $ }}
        property: {{ tpl (.property | default "") $ }}
        version: {{ .version | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
