apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if and .Values.service.ports }}
    {{- range $name, $config := .Values.service.ports }}
    - port: {{ $config.port }}
      targetPort: {{ $config.targetPort | default "http" }}
      protocol: {{ $config.protocol | default "TCP" }}
      name: {{ $config.name | default "http" }}
    {{- end }}
    {{ else }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
